Update CodeQL
CodeQL

Error: Encountered a fatal error while running
"/opt/hostedtoolcache/CodeQL/2.23.9/x64/codeql/codeql database init
--force-overwrite --db-cluster /home/runner/work/_temp/codeql_databases
--source-root=/home/runner/work/textfsm-rs/textfsm-rs
--calculate-language-specific-baseline --extractor-include-aliases
--sublanguage-file-coverage --language=rust
--codescanning-config=/home/runner/work/_temp/user-config.yaml
--build-mode=manual". Exit code was 2 and error was: A fatal error
occurred: Rust does not support the manual build mode. Please try using
one of the following build modes instead: none. See the logs for more
details.